# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sergey Shostko
email: s.shostko@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics: UA-75610602-4

author:
  name: Sergey Shostko
  email: s.shostko@gmail.com
  github: shostko
  skype: s.shostko
  linkedin: sergeyshostko
  twitter: SergeyShostko
  playconsole: 8208994608755751630
  bio: Android Group Lead @instinctools
  email_md5: 42dfae824cdccebc0e9180487d59ccb0Ñƒ

BASE_PATH:

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
#  - jekyll-feed
#  - jekyll-paginate

collections:
  projects:
    output: false
  own:
    output: true
    permalink: /project/:title

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      side: false
      url_local: false
  - scope:
      path: ""
      type: "own"
    values:
      layout: "project"
      own: true
      url_local: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
